version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desconto_inss_api_development
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:migrate db:seed && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/desconto_inss_api_development
      -RAILS_ENV: production
      SECRET_KEY_BASE: <%= ENV["SECRET_KEY_BASE"] %>

volumes:
  db_data:
