require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/applicant_reports", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ApplicantReport. As you add validations to ApplicantReport, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ApplicantReport.create! valid_attributes
      get applicant_reports_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      applicant_report = ApplicantReport.create! valid_attributes
      get applicant_report_url(applicant_report)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_applicant_report_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      applicant_report = ApplicantReport.create! valid_attributes
      get edit_applicant_report_url(applicant_report)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ApplicantReport" do
        expect {
          post applicant_reports_url, params: { applicant_report: valid_attributes }
        }.to change(ApplicantReport, :count).by(1)
      end

      it "redirects to the created applicant_report" do
        post applicant_reports_url, params: { applicant_report: valid_attributes }
        expect(response).to redirect_to(applicant_report_url(ApplicantReport.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ApplicantReport" do
        expect {
          post applicant_reports_url, params: { applicant_report: invalid_attributes }
        }.to change(ApplicantReport, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post applicant_reports_url, params: { applicant_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested applicant_report" do
        applicant_report = ApplicantReport.create! valid_attributes
        patch applicant_report_url(applicant_report), params: { applicant_report: new_attributes }
        applicant_report.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the applicant_report" do
        applicant_report = ApplicantReport.create! valid_attributes
        patch applicant_report_url(applicant_report), params: { applicant_report: new_attributes }
        applicant_report.reload
        expect(response).to redirect_to(applicant_report_url(applicant_report))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        applicant_report = ApplicantReport.create! valid_attributes
        patch applicant_report_url(applicant_report), params: { applicant_report: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested applicant_report" do
      applicant_report = ApplicantReport.create! valid_attributes
      expect {
        delete applicant_report_url(applicant_report)
      }.to change(ApplicantReport, :count).by(-1)
    end

    it "redirects to the applicant_reports list" do
      applicant_report = ApplicantReport.create! valid_attributes
      delete applicant_report_url(applicant_report)
      expect(response).to redirect_to(applicant_reports_url)
    end
  end
end
